from .triangle_wave_controller import NODE_CLASS_MAPPINGS as TWC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TWC_DISPLAY
from .triangle_wave_controller_advanced import NODE_CLASS_MAPPINGS as TWCA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TWCA_DISPLAY
from .video_iterative_sampler import NODE_CLASS_MAPPINGS as VIS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIS_DISPLAY
from .video_iterative_sampler_advanced import NODE_CLASS_MAPPINGS as VISA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISA_DISPLAY
from .wave_visualizer import NODE_CLASS_MAPPINGS as WV_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WV_DISPLAY
from .wave_style_model_apply import NODE_CLASS_MAPPINGS as WSMA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WSMA_DISPLAY
from .wave_clip_vision_encode import NODE_CLASS_MAPPINGS as WCV_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WCV_DISPLAY
from .wave_ipadapter_controller import NODE_CLASS_MAPPINGS as WIPC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WIPC_DISPLAY
from .wave_ipadapter_advanced import NODE_CLASS_MAPPINGS as WIPA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WIPA_DISPLAY
from .wave_controlnet_apply import NODE_CLASS_MAPPINGS as WCNA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WCNA_DISPLAY
from .wave_controlnet_controller import NODE_CLASS_MAPPINGS as WCNC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WCNC_DISPLAY
from .video_checkpoint_controller import NODE_CLASS_MAPPINGS as VCC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VCC_DISPLAY

NODE_CLASS_MAPPINGS = {
    **TWC_MAPPINGS,
    **TWCA_MAPPINGS,
    **VIS_MAPPINGS,
    **VISA_MAPPINGS,
    **WV_MAPPINGS,
    **WSMA_MAPPINGS,
    **WCV_MAPPINGS,
    **WIPC_MAPPINGS,
    **WIPA_MAPPINGS,
    **WCNA_MAPPINGS,
    **WCNC_MAPPINGS,
    **VCC_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TWC_DISPLAY,
    **TWCA_DISPLAY,
    **VIS_DISPLAY,
    **VISA_DISPLAY,
    **WV_DISPLAY,
    **WSMA_DISPLAY,
    **WCV_DISPLAY,
    **WIPC_DISPLAY,
    **WIPA_DISPLAY,
    **WCNA_DISPLAY,
    **WCNC_DISPLAY,
    **VCC_DISPLAY,
}

WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
