from .nodes.video_wave_controller import NODE_CLASS_MAPPINGS as WC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WC_DISPLAY
from .nodes.image_wave_controller import NODE_CLASS_MAPPINGS as IWC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IWC_DISPLAY
from .nodes.interpolation_wave_controller import NODE_CLASS_MAPPINGS as INTWC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INTWC_DISPLAY
from .nodes.video_iterative_sampler import NODE_CLASS_MAPPINGS as VIS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIS_DISPLAY
from .nodes.image_iterative_sampler import NODE_CLASS_MAPPINGS as IIS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IIS_DISPLAY
from .nodes.video_interpolate_sampler import NODE_CLASS_MAPPINGS as VIN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIN_DISPLAY
from .nodes.wave_visualizer import NODE_CLASS_MAPPINGS as WV_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WV_DISPLAY
from .nodes.wave_style_model_apply import NODE_CLASS_MAPPINGS as WSMA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WSMA_DISPLAY
from .nodes.wave_clip_vision_encode import NODE_CLASS_MAPPINGS as WCV_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WCV_DISPLAY
from .nodes.wave_ipadapter_controller import NODE_CLASS_MAPPINGS as WIPC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WIPC_DISPLAY
from .nodes.wave_ipadapter_advanced import NODE_CLASS_MAPPINGS as WIPA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WIPA_DISPLAY
from .nodes.wave_controlnet_apply import NODE_CLASS_MAPPINGS as WCNA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WCNA_DISPLAY
from .nodes.wave_controlnet_controller import NODE_CLASS_MAPPINGS as WCNC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WCNC_DISPLAY
from .nodes.iterative_checkpoint_controller import NODE_CLASS_MAPPINGS as ICC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ICC_DISPLAY
from .nodes.checkpoint_preview_loader import NODE_CLASS_MAPPINGS as CPL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CPL_DISPLAY
from .nodes.explorer_conditioning_wave_controller import NODE_CLASS_MAPPINGS as ECWC_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ECWC_DISPLAY
from .nodes.explorer_conditioning_sampler import NODE_CLASS_MAPPINGS as ECS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ECS_DISPLAY

NODE_CLASS_MAPPINGS = {
    **WC_MAPPINGS,
    **IWC_MAPPINGS,
    **INTWC_MAPPINGS,
    **VIS_MAPPINGS,
    **IIS_MAPPINGS,
    **VIN_MAPPINGS,
    **WV_MAPPINGS,
    **WSMA_MAPPINGS,
    **WCV_MAPPINGS,
    **WIPC_MAPPINGS,
    **WIPA_MAPPINGS,
    **WCNA_MAPPINGS,
    **WCNC_MAPPINGS,
    **ICC_MAPPINGS,
    **CPL_MAPPINGS,
    **ECWC_MAPPINGS,
    **ECS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **WC_DISPLAY,
    **IWC_DISPLAY,
    **INTWC_DISPLAY,
    **VIS_DISPLAY,
    **IIS_DISPLAY,
    **VIN_DISPLAY,
    **WV_DISPLAY,
    **WSMA_DISPLAY,
    **WCV_DISPLAY,
    **WIPC_DISPLAY,
    **WIPA_DISPLAY,
    **WCNA_DISPLAY,
    **WCNC_DISPLAY,
    **ICC_DISPLAY,
    **CPL_DISPLAY,
    **ECWC_DISPLAY,
    **ECS_DISPLAY,
}

WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
